auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Something Li is interested in
url: aikinogard.github.io
feed: /atom.xml
author_info: <a href="aikinogard.github.io/">Li Li</a>
